services:
  - type: web
    name: dtms2
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: cd target && java -jar DTMS2-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: JAVA_VERSION
        value: 17