services:
  - type: web
    name: dtms2
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d4jjll4hg0os73brtjk0-a.oregon-postgres.render.com/fitnessdb_5iw2?ssl=true&sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: fitnessdb_5iw2_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: ZpTdhI43Z8nmn39RyWFPOXEnuGoRrBGR
      - key: SERVER_PORT
        value: 8080
      - key: PORT
        value: 8080