services:
  - type: web
    name: dtms2
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/DTMS2-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_URL
        value: jdbc:postgresql://dpg-d4jjll4hg0os73brtjk0-a.oregon-postgres.render.com/fitnessdb_5iw2
      - key: JDBC_DATABASE_USERNAME
        value: fitnessdb_5iw2_user
      - key: JDBC_DATABASE_PASSWORD
        value: ZpTdhI43Z8nmn39RyWFPOXEnuGoRrBGR